### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by iam-py-test**

### CODE REVIEW

**Review by iam-py-test — COMMENTED** [review]
This was recommended by GitHub

**Review by iam-py-test — COMMENTED** [review]
Is it acceptable to use Issues for this, or do you want to add your email or another form of communication?

**Comment by donno2048** [comment]
If you add a Code of conduct we should add contributing guidelines and issue and pull request templates

It is fine for me (and feel free to merge it) but right now, we didn't get any help offered (and don't expect to get) and didn't even share this in the main issue it came from...

**Comment by donno2048** [comment]
I created a _CONTRIBUTING.md_...

**Comment by iam-py-test** [comment]
Issue templates added. Do they look ok?

**Comment by donno2048** [comment]
They are looking awesome

**Pull request merged**
