### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by iam-py-test**
Add code scanning for security issues

### CODE REVIEW

**Review by iam-py-test — COMMENTED** [review]
@donno2048 are you ok with this?

**Comment by donno2048** [comment]
You didn't set the python version and I'm pretty sure it defaults to python2.7

**Comment by iam-py-test** [comment]
> Two issues:
> 
> 1. Is CodeQL automatically installed? because I didn't install it
> 2. You didn't set the python version and I'm pretty sure it defaults to python2.7
> 
> Edit: It seems CodeQL is really automatically installed...

I use it on my repos for code scanning, and thought it might be helpful here.
How do I set the version?

**Comment by donno2048** [comment]
> How do I set the version?

I think it's like that:

```yml
    strategy:
      fail-fast: false
      matrix:
        python: [3.7, 3.8]
```

**Comment by iam-py-test** [comment]
> > How do I set the version?
> 
> I think it's like that:
> 
> ```yaml
>     strategy:
>       fail-fast: false
>       matrix:
>         python: [3.7, 3.8]
> ```

Fixed. Thanks for your help!

**Comment by donno2048** [comment]
> > > How do I set the version?
> > 
> > 
> > I think it's like that:
> > ```yaml
> >     strategy:
> >       fail-fast: false
> >       matrix:
> >         python: [3.7, 3.8]
> > ```
> 
> Fixed. Thanks for your help!

I'm waiting to see the checks won't fail, then I will merge it

**Pull request merged**
