### PR TITLE
create a package

### PR DESCRIPTION
**Pull request by donno2048**
This cannot be merged until #6 will be resolved

### CODE REVIEW

**Review by iam-py-test — APPROVED** [review]
This seems ok.

**Comment by donno2048** [comment]
Fixed #6 (I will check it to make sure)

And some explanation need to be added to the README

**Comment by iam-py-test** [comment]
I agree that the README needs some work.
I will try to improve it

**Comment by iam-py-test** [comment]
@donno2048 it seems that packages with a `-` in their name fail. Maybe we should rename to `restrictedfunctions`

**Comment by donno2048** [comment]
> @donno2048 it seems that packages with a `-` in their name fail. Maybe we should rename to `restrictedfunctions`

```bash
> pip3 install restricted-functions
....
> python3
```
```py
>>> import ref
>>> ref.main(__builtins__)
>>> import os
>>> os.system
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'os' has no attribute 'system'
```

**Comment by iam-py-test** [comment]
Oh. Strange.
Maybe that only occurs when importing files not packages. (Just for me, I found that my package simple-bcrypt failed to load until I renamed simple-bcrypt.py to simplebcrypt.py)

**Comment by donno2048** [comment]
> Oh. Strange.
> Maybe that only occurs when importing files not packages. (Just for me, I found that my package simple-bcrypt failed to load until I renamed simple-bcrypt.py to simplebcrypt.py)

Have you tried simple_bcrypt?

**Comment by iam-py-test** [comment]
> > Oh. Strange.
> > Maybe that only occurs when importing files not packages. (Just for me, I found that my package simple-bcrypt failed to load until I renamed simple-bcrypt.py to simplebcrypt.py)
> 
> Have you tried simple_bcrypt?

I tried simplebcrypt and it worked, but I did not try `simple_bcrypt`.
Does the modified code on #9  look better?

**Pull request merged**
