### PR TITLE
Add silent mode

### PR DESCRIPTION
**Pull request by iam-py-test**

### CODE REVIEW

**Comment by donno2048** [comment]
I'll start implementing it in a minute...

**Comment by donno2048** [comment]
Before you continue, I have another implementation I want to try, I will open a new branch...

You can keep doing what you're doing but bear in mind it might not the ideal solution in this case

**Comment by iam-py-test** [comment]
@donno2048 maybe we could use an list of all the functions, and then call it via `del M[currentname]`

**Comment by donno2048** [comment]
> Before you continue, I have another implementation I want to try, I will open a new branch...
> 
> You can keep doing what you're doing but bear in mind it might not the ideal solution in this case

Tried my solution, it's not as elegant as I thought...

**Comment by donno2048** [comment]
> @donno2048 maybe we could use an list of all the functions, and then call it via `del M[currentname]`

Actually, that was the original intention I honestly forgot about it, I meant it to be a loop...

**Comment by iam-py-test** [comment]
> > Before you continue, I have another implementation I want to try, I will open a new branch...
> > You can keep doing what you're doing but bear in mind it might not the ideal solution in this case
> 
> Tried my solution, it's not as elegant as I thought...

What was your solution? We might be able to modify it to work better

**Comment by donno2048** [comment]
> > > Before you continue, I have another implementation I want to try, I will open a new branch...
> > > You can keep doing what you're doing but bear in mind it might not the ideal solution in this case
> > 
> > 
> > Tried my solution, it's not as elegant as I thought...
> 
> What was your solution? We might be able to modify it to work better

I used a wrapper, which takes the `silent` variable and returns either an empty return or an empty function

**Comment by donno2048** [comment]
> @donno2048 maybe we could use an list of all the functions, and then call it via `del M[currentname]`

I will implement that in the main branch (as it is not related specifically to this issue) and you could rebase

**Comment by donno2048** [comment]
> > @donno2048 maybe we could use an list of all the functions, and then call it via `del M[currentname]`
> 
> I will implement that in the main branch (as it is not related specifically to this issue) and you could rebase

Do you think that format is good?

```py
{
    "os": ["system", "open", ...],
    ...
}
```

**Comment by iam-py-test** [comment]
> > > @donno2048 maybe we could use an list of all the functions, and then call it via `del M[currentname]`
> > 
> > 
> > I will implement that in the main branch (as it is not related specifically to this issue) and you could rebase
> 
> Do you think that format is good?
> 
> ```python
> {
>     "os": ["system", "open", ...],
>     ...
> }
> ```

Yep! Thank looks great
This should make this easier to maintain

**Comment by donno2048** [comment]
Moving to #20 because the conflict is unresolvable

**Pull request closed without merging**
