### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by iam-py-test**
Is this look ok?
It still needs to be completed and I am not sure if the Python code is valid

### CODE REVIEW

**Comment by donno2048** [comment]
> Is this look ok?
> It still needs to be completed and I am not sure if the Python code is valid

The python code is not right, look a my comment https://github.com/donno2048/restricted-functions/pull/8#issuecomment-862551986

**Comment by donno2048** [comment]
Ok, if you have python2 installed then the pip command will be used for it, so you should probably use "pip3"

Secondly, I think usually it's best to split into two different sections: `Usage` and `Installation`

**Comment by donno2048** [comment]
I made several modifications feel free to change it

**Comment by iam-py-test** [comment]
> I made several modifications feel free to change it

Your modifications look good.
However,you might want to delete my original How to use at the top

**Comment by donno2048** [comment]
> > I made several modifications feel free to change it
> 
> Your modifications look good.
> However,you might want to delete my original How to use at the top

I just saw it, thanks

**Comment by iam-py-test** [comment]
I need to do something off the computer so will not see notifications for a while

**Pull request merged**
