### PR TITLE
Add security levels

### PR DESCRIPTION
**Pull request by iam-py-test**

### CODE REVIEW

**Comment by donno2048** [comment]
Do you think `os.unlink`, `os.rmdir`, `shutil.rmtree`, `os.remove`, ` pathlib.Path.rmdir`, `pathlib.Path.unlink` and `os.removedirs` should be in level number 1?

**Comment by iam-py-test** [comment]
> Do you think `os.unlink`, `os.rmdir`, `shutil.rmtree`, `os.remove`, ` pathlib.Path.rmdir`, `pathlib.Path.unlink` and `os.removedirs` should be in level number 1?

Edit: I think those should be L1

**Comment by donno2048** [comment]
About `os.fork`, `os.forkpty`, `os.plock`, I'm not sure whether they should be in level 1 or level 0, because the harm is temporary (maybe even level 2?),

and since we have only two levels it could also be a flag (e.g. `extra_protection`)

**Comment by iam-py-test** [comment]
> About `os.fork`, `os.forkpty`, `os.plock`, I'm not sure whether they should be in level 1 or level 0,
> 
> and since we have only two levels it could also be a flag (e.g. `extra_protection`)

I think they should be 0, as they are similar to the other 0 funcs.

**Comment by donno2048** [comment]
> > About `os.fork`, `os.forkpty`, `os.plock`, I'm not sure whether they should be in level 1 or level 0,
> > and since we have only two levels it could also be a flag (e.g. `extra_protection`)
> 
> I think they should be 0, as they are similar to the other 0 funcs.

OK

**Comment by iam-py-test** [comment]
> > > About `os.fork`, `os.forkpty`, `os.plock`, I'm not sure whether they should be in level 1 or level 0,
> > > and since we have only two levels it could also be a flag (e.g. `extra_protection`)
> > 
> > 
> > I think they should be 0, as they are similar to the other 0 funcs.
> 
> OK

Or have a flag like `blockfork` that prevents forking
I don't know how many benign uses there are for them

**Comment by donno2048** [comment]
> > > > About `os.fork`, `os.forkpty`, `os.plock`, I'm not sure whether they should be in level 1 or level 0,
> > > > and since we have only two levels it could also be a flag (e.g. `extra_protection`)
> > > 
> > > 
> > > I think they should be 0, as they are similar to the other 0 funcs.
> > 
> > 
> > OK
> 
> Or have a flag like `blockfork` that prevents forking

It will probably be best but then it'll make sense to remove the `level` completely and use this flag and a `filechange` flag or something (or extend the `restrictwrite` we already have)

**Comment by iam-py-test** [comment]
Maybe have a `blockdelete` flag for removing files and a `protectdirs` flag for dirs

**Comment by donno2048** [comment]
> Maybe have a `blockdelete` flag for removing files and a `protectdirs` flag for dirs

So `blockdelete`, `protectdirs` and `restrictwrite`?

**Comment by donno2048** [comment]
Better just have `protectdirs` and `protectfiles` I think

**Comment by iam-py-test** [comment]
> Better just have `protectdirs` and `protectfiles` I think

Ok. Updating

**Comment by donno2048** [comment]
We need to update the docs and the docstrings

**Comment by iam-py-test** [comment]
I will get the README.md
It looks like the action has already updated the other Docs

**Comment by donno2048** [comment]
> It looks like the action has already updated the other Docs

Yeah, but in order to update them correctly the docstrings need to be updated too

**Comment by donno2048** [comment]
The last thing left to do before merging is to decide how to treat `os.chmod` and `pathlib.Path.chmod`

**Comment by iam-py-test** [comment]
> The last thing left to do before merging is to decide how to treat `os.chmod` and `pathlib.Path.chmod`

Maybe add another option like `lockperms`, or add them when file deletion is denied
<details>
<summary>Off topic</summary>
I looked at the pyip page on this project & it looks good.
Maybe we should link to it somewhere...
</details>

**Comment by donno2048** [comment]
> Maybe add another option like `lockperms`

That what I was thinking of

**Comment by donno2048** [comment]
I'll left this `chmod` as an open issue for now and merge

**Comment by donno2048** [comment]
> I looked at the pyip page on this project & it looks good. Maybe we should link to it somewhere...

I'm going to do that when we will release it officially

**Pull request merged**
